# Generated by Django 5.2 on 2025-06-14 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTOMOVEL', 'Automóvel'), ('MOTOCICLETA', 'Motocicleta')], max_length=15, verbose_name='Tipo do Veículo')),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_plate', message='A placa deve estar no formato Mercosul (LLLNXNN) ou anterior (LLLNNNN).', regex='^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$|^[A-Z]{3}[0-9]{4}$')], verbose_name='Placa')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano_fabricacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='O ano de fabricação não pode ser anterior a 1900.'), django.core.validators.MaxValueValidator(2026, message='O ano de fabricação não pode ser futuro.')], verbose_name='Ano de Fabricação')),
                ('quilometragem_atual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='A quilometragem não pode ser negativa.')], verbose_name='Quilometragem Atual')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Outras Informações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
    ]
