# Generated by Django 5.2 on 2025-06-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_departamento', models.CharField(blank=True, help_text='Código único para identificação do departamento.', max_length=50, null=True, unique=True, verbose_name='Código do Departamento')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Departamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
    ]
