# Generated by Django 5.2 on 2025-06-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empregados', '0001_initial'),
        ('servicos', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_os', models.CharField(blank=True, help_text='Código único gerado automaticamente para a Ordem de Serviço.', max_length=50, null=True, unique=True, verbose_name='Código da O.S.')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora Emissão')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Em Andamento', 'Em Andamento'), ('Aguardando Peças', 'Aguardando Peças'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Aberta', max_length=20, verbose_name='Status da O.S.')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total da O.S.')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente', verbose_name='Cliente')),
                ('empregado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_responsavel', to='empregados.empregado', verbose_name='Empregado Responsável')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_detalhada', models.TextField(verbose_name='Descrição Detalhada do Item')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total do Item')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_ordem_servico', to='servicos.servico', verbose_name='Tipo de Serviço')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordem_servico.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Serviço',
                'verbose_name_plural': 'Itens da Ordem de Serviço',
                'unique_together': {('ordem_servico', 'servico', 'descricao_detalhada')},
            },
        ),
    ]
