# Generated by Django 5.2 on 2025-06-12 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empregado', models.CharField(blank=True, help_text='Código único gerado automaticamente para o empregado.', max_length=50, null=True, unique=True, verbose_name='Código do Empregado')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('codigo_dependentes', models.CharField(blank=True, help_text='Código para identificação de dependentes do empregado (opcional).', max_length=50, null=True, verbose_name='Código de Dependentes')),
                ('cargo', models.CharField(choices=[('Gerente', 'Gerente'), ('Supervisor', 'Supervisor'), ('Mecânico', 'Mecânico'), ('Vendedor', 'Vendedor'), ('Atendente', 'Atendente'), ('Administrativo', 'Administrativo'), ('Outro', 'Outro')], default='Outro', max_length=50, verbose_name='Cargo')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('naturalidade', models.CharField(max_length=100, verbose_name='Naturalidade')),
                ('cidade_residencia', models.CharField(max_length=100, verbose_name='Cidade de Residência')),
                ('uf_residencia', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF de Residência')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo'), ('Separado', 'Separado'), ('União Estável', 'União Estável')], default='Solteiro', max_length=20, verbose_name='Estado Civil')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empregados', to='departamentos.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Empregado',
                'verbose_name_plural': 'Empregados',
                'ordering': ['nome_completo'],
            },
        ),
    ]
