# Generated by Django 5.2 on 2025-06-08 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_servico', models.CharField(help_text='Código único para identificar o serviço.', max_length=50, unique=True, verbose_name='Código do Serviço')),
                ('tipo_servico', models.CharField(choices=[('B', 'Balanceamento'), ('A', 'Alinhamento'), ('R', 'Reforma de Rodas'), ('O', 'Outro')], max_length=1, verbose_name='Tipo do Serviço')),
                ('tipo_servico_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name="Especifique o Tipo do Serviço (se 'Outro')")),
                ('descricao_detalhada', models.TextField(blank=True, help_text='Informações adicionais sobre o serviço.', null=True, verbose_name='Descrição Detalhada do Serviço')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='O valor unitário deve ser um número positivo.')], verbose_name='Valor Unitário')),
                ('tempo_medio_execucao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O tempo médio de execução deve ser um número inteiro positivo.')], verbose_name='Tempo Médio de Execução')),
                ('unidade_tempo', models.CharField(choices=[('H', 'Horas'), ('M', 'Minutos')], default='M', max_length=1, verbose_name='Unidade de Tempo')),
                ('quantidade_rodas', models.IntegerField(blank=True, help_text='Número de rodas envolvidas no serviço (opcional).', null=True, validators=[django.core.validators.MinValueValidator(1, message='A quantidade de rodas deve ser um número inteiro positivo.')], verbose_name='Quantidade Padrão de Rodas')),
                ('prazo_entrega_dias', models.IntegerField(blank=True, help_text='Prazo em dias para a conclusão do serviço (opcional).', null=True, validators=[django.core.validators.MinValueValidator(1, message='O prazo de entrega deve ser um número inteiro positivo.')], verbose_name='Prazo de Entrega Padrão (dias)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['codigo_servico'],
            },
        ),
    ]
